platform :ios, '10.0'
use_frameworks!

target 'YiWuShuang' do
  pod 'AFNetworking', '~> 4.0'
  pod 'Masonry'
  pod 'YYKit'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'YYModel'
  pod  'YKWoodpecker'
  pod 'CYLTabBarController', '~> 1.24.0'

end
