source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!

target 'YiWuShuang' do
  pod 'AFNetworking', '~> 4.0'
  pod 'Masonry'
  pod 'YYKit'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'YYModel'
  pod  'YKWoodpecker'
  pod 'SDWebImage', '~> 5.0'
  
  pod 'mob_sharesdk'
  pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
  pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
  pod 'mob_sharesdk/ShareSDKRestoreScene'
  pod 'mob_sharesdk/ShareSDKPlatforms/Messenger'


end
